// This file is auto-generated by @hey-api/openapi-ts

export const RatingSchema = {
    type: 'object',
    properties: {
        rate: {
            type: 'number'
        },
        count: {
            type: 'integer'
        }
    },
    required: ['rate', 'count']
} as const;

export const ProductSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        },
        title: {
            type: 'string'
        },
        price: {
            type: 'number'
        },
        description: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        image: {
            type: 'string'
        },
        rating: {
            '$ref': '#/components/schemas/Rating'
        }
    },
    required: ['id', 'title', 'price', 'description', 'category', 'image']
} as const;