// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetProductsError, GetProductsResponse, GetProductByIdData, GetProductByIdError, GetProductByIdResponse } from './types.gen';

export const client = createClient(createConfig());

export const getProducts = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetProductsResponse, GetProductsError, ThrowOnError>({
    ...options,
    url: '/products'
}); };

export const getProductById = <ThrowOnError extends boolean = false>(options: Options<GetProductByIdData, ThrowOnError>) => { return (options?.client ?? client).get<GetProductByIdResponse, GetProductByIdError, ThrowOnError>({
    ...options,
    url: '/products/{id}'
}); };