// This file is auto-generated by @hey-api/openapi-ts

export type Rating = {
    rate: number;
    count: number;
};

export type Product = {
    id: number;
    title: string;
    price: number;
    description: string;
    category: string;
    image: string;
    rating?: Rating;
};

export type GetProductsResponse = (Array<Product>);

export type GetProductsError = unknown;

export type GetProductByIdData = {
    path: {
        id: number;
    };
};

export type GetProductByIdResponse = (Product);

export type GetProductByIdError = unknown;